app:
  name: hobbify

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hobbify_master
    username: hobbify
    password: root
    driver-class-name:  org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      dll-aut: update
  liquibase:
    change-log: classpath:/liquibase/masterChangeLog.xml
    enabled: false

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: proiectic
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.bfwg: DEBUG

server:
  port: 8080
